name: Deploy Scripts to S3
on:
  push:
    branches:
      - main
    # Only run if files in the below folders change
    paths:
      - 'scripts/**'
      - 'step_functions/**'
      - 'cloud_formation/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync scripts to S3
        # To copy local scripts folder to S3 bucket
        run: |
          aws s3 sync ./scripts s3://nyc-taxi-dev-raw-206617159909/scripts/ --delete

      # Upload the Step Function JSON to S3
      - name: Upload SF Definition to S3
        run: |
          aws s3 cp ./step_functions/nyc-taxi-sf.json s3://nyc-taxi-dev-raw-206617159909/sf_scripts/nyc-taxi-sf.json
          sleep 10 

      # Deploy CloudFormation 
      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: nyc-yellow-taxi-stack
          template: cloud_formation/nyc-taxi-infra.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            ProjectName=nyc-taxi,
            Env=dev