name: Deploy Scripts to S3
on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**' # Only run if files in the scripts folder change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync scripts to S3
        # To copy local scripts folder to S3 bucket
        run: |
          aws s3 sync ./scripts s3://nyc-taxi-dev-raw-206617159909/scripts/ --delete

      - name: Prepare Step Function Definition
        id: sf_def
        # allows long, complex strings to be stored safely in single line
        run: |
          B64_JSON=$(jq -c . step_functions/nyc-taxi-sf.json | base64 -w 0)
          echo "definition=$B64_JSON" >> $GITHUB_OUTPUT

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name nyc-yellow-taxi-stack \
            --template-file cloud_formation/nyc-taxi-infra.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
                ProjectName=nyc-taxi \
                Env=dev \
                StepFunctionDefinition='${{ steps.sf_def.outputs.definition }}'